name: Email GHAS Reports

on:
  schedule:
    - cron: '00 00 * * *' # Run at 00:00 UTC every night

jobs:
  run_script_and_send_email:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Clone specific repository
        run: git clone https://github.com/rhe8502/ghas_report.git

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          . venv/bin/activate
          pip install -r ./ghas_report/requirements.txt

      - name: Generate JSON configuration file
        run: |
          echo '{
            "connection": {
              "gh_api_url": "https://api.github.com",
              "gh_api_key": ""
            },
            "location": {
              "reports": "",
              "keyfile": ""
            },
            "projects": {
              "YOUR_PROJECT": {
                "owner": "OWNER",
                "organizations": [
                  "YOUR_ORG"
                ],
                "repositories": [
                  "YOUR_REPO"
                ]
              }
            }
          }' > ./ghas_report/src/ghas_config.json

      - name: Run Python script
        run: |
          . venv/bin/activate
          python ./ghas_report/src/ghas_report.py --all --xlsx -lr ./ghas_report/reports
        env:
          GH_API_KEY: ${{ secrets.GH_API_KEY }}

      - name: Send CSV files via email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Github Advandced Security Reports
          body: Please find the attached vulnerability report(s) generated by the GitHub Actions workflow.
          to: your_email@example.com
          from: GitHub Action <sender_email@gmail.com>
          attachments: ./ghas_report/reports/*.*