name: Email CSV Workflow

on:
  schedule:
    - cron: '15 22 * * *'

jobs:
  send_csv_files_via_email:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Clone specific repository
        run: git clone https://github.com/rhe8502/ghas_report.git

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate JSON configuration file
        run: |
          echo '{
            "connection": {
                    "gh_api_url": "",
                    "gh_api_key": ""
                },
                "location": {
                    "reports": "",
                    "keyfile": ""
                },
                "projects": {
                    "SKYNET": {
                        "owner": "rhe8502",
                        "organizations": [
                            "akigakita"
                        ],
                        "repositories": [
                            "sectest"
                        ]
                    }
                }
            }
          }' > ghas_config.json

      - name: Run Python script
        run: python ghas_report.py -l
        env:
          GH_API_KEY: ${{ secrets.GH_API_KEY }}

      - name: Send CSV files via email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "CSV files from GitHub Actions"
          body: "Please find the attached CSV files generated by the GitHub Actions workflow."
          to: rhe8502@pm.me
          from: GitHub Action <rhe8502@gmail.com>
          content_type: text/html
          attachments: "*.csv"
