name: Toot on Release

on:
  workflow_dispatch:
  # release:
  #  types:
  #    - published

jobs:
  toot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Mastodon.py

    - name: Send Toot
      env:
        MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
      run: |
        python -c '
        import os
        from mastodon import Mastodon

        api_base_url = "https://infosec.exchange"
        access_token = os.environ["MASTODON_ACCESS_TOKEN"]
        release_tag = "${{ github.event.release.tag_name }}"
        release_url = "${{ github.event.release.html_url }}"

        Mastodon.api_base_url = api_base_url
        mastodon = Mastodon(access_token=access_token, api_base_url=api_base_url)
        status = f"📢 GHAS Reporting Tool {release_tag} - a Python script to fetch GitHub Advanced Security (GHAS) alerts and generate reports in CSV and JSON formats. Download the release and consult the README for setup details.\n#GitHub #NewRelease #GHAS #AppSec #InfoSec\n\n{release_url}"
        mastodon.status_post(status)
        '