name: Toot on Release

on:
  release:
    types:
      - published

jobs:
  toot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Mastodon.py

    - name: Send Toot
      env:
        MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
      run: |
        python -c '
        python post_to_mastodon.py
import os

api_base_url = "https://infosec.exchange"
access_token = os.environ["MASTODON_ACCESS_TOKEN"]

release_url = "${{ github.event.release.html_url }}"

Mastodon.api_base_url = api_base_url
mastodon = Mastodon(access_token=access_token)
status = f"🚀 GHAS Reporting Tool v1.0.0 - Initial Release! A Python script to fetch GitHub Advanced Security (GHAS) alerts and generate reports in CSV and JSON formats. Download the release and check the README for setup details {release_url} #GitHub #NewRelease #GHAS #AppSec #InfoSec "
mastodon.status_post(status)
'
